### ISSUE TITLE
小米8手机    第二排与效果图不一致

### ISSUE THREAD

**Issue by renhuan** [wenjiangit/LoopBanner#2]
[
![b9c5c42f1d35687504e6e6d4bd02d5b](https://user-images.githubusercontent.com/15374282/53854039-e2c22f80-4002-11e9-8bc7-fa6af6660652.jpg)
](url)

**Comment by wenjiangit** [comment]
这个是因为demo和效果图没有及时更新哈,你可以把代码下载下来,然后运行一下,可以看到最新的效果,谢谢
@renhuan2015

**Comment by renhuan** [comment]
> 这个是因为demo和效果图没有及时更新哈,你可以把代码下载下来,然后运行一下,可以看到最新的效果,谢谢
> @renhuan2015

好的
